name: OnGitHub

on:
  push:
    branches: [ pz/manual-appcast ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: xcodebuild -workspace SpartaConnect.xcworkspace -scheme App build | xcpretty
    - name: Run tests
      run: xcodebuild -workspace SpartaConnect.xcworkspace -scheme App test | xcpretty
