name: on-github

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:

    runs-on: macos-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
    - name: Disable firewall
      run: |
        sudo /usr/libexec/ApplicationFirewall/socketfilterfw --setglobalstate off
        sudo /usr/libexec/ApplicationFirewall/socketfilterfw -k
#   Breaks clicking on menu bar button
#    - name: Close Finder windows
#      run: launchctl unload /System/Library/LaunchAgents/com.apple.Finder.plist
    - name: Close Notification window
      run: killall UserNotificationCenter || true
    - uses: apple-actions/import-codesign-certs@v1
      id: codesign
      with:
        p12-file-base64: ${{ secrets.CERTIFICATES_P12 }}
        p12-password: ${{ secrets.CERTIFICATES_P12_PASSWORD }}
        keychain: certs
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: ./vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
    - name: Our Commands pwd
      run: pwd
    - name: ls -la
      run: ls -la
    - name: gem environment
      run: gem environment
    - name: ruby version
      run: ruby --version
#    - run: ls -l vendor/bundle/ruby/
#    - run: gem install bundler -v 2.1.4
    - name: bundle
      run: |
        bundle config path ./vendor/bundle
        bundle install --jobs 4 --retry 3
    - name: pod install
      run: pod install
    - run: pod update
    - run: git diff
    - name: Unit Specs
      run: set -o pipefail && xcodebuild -workspace SpartaConnect.xcworkspace -scheme Testable test | xcpretty
