name: OnGitHub

on:
  push:
    branches: [ master, dirt-ball ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: xcodebuild -workspace SpartaConnect.xcworkspace -scheme App build | xcpretty
    - name: Run Unit Specs
      run: xcodebuild -workspace SpartaConnect.xcworkspace -scheme App test -only-testing UnitSpecs | xcpretty
    - name: Start HTTP mock server
      run: |
        cd UITests/mockHttpServer
        python -m SimpleHTTPServer &
    - name: Run UI Tests
      run: xcodebuild -workspace SpartaConnect.xcworkspace -scheme App test -only-testing UITests -resultBundlePath test-results | xcpretty
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: ui-tests.xcresult.zip
        path: test-results.xcresult/
